[package]
name = "x402-reqwest-example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
x402-reqwest = { version = "0.4" }
x402-rs = { version = "0.10" }
reqwest = { version = "0.12.20" }
tokio = { version = "1.45.1" }
dotenvy = { version = "0.15.7" }

# EVM: Alloy
alloy-signer-local = { version = "1.1.3" }

# Solana
solana-rpc-client = { version = "2.3.13" }
solana-keypair = { version = "2.2.3" }