[package]
name = "x402-chain-eip155"
version = "0.1.0"
edition = "2024"

[dependencies]  # FIXME Features schemes, facilitator, server, client
serde = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
dashmap = { version = "6.1.0" }
tower = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }

x402-types = { path = "../../x402-types" }
rand = { version = "0.9.2" }

# Alloy
alloy-primitives = { version = "1.4.1" }
alloy-provider = { version = "1.1.3" }
alloy-network = { version = "1.1.3" }
alloy-rpc-client = { version = "1.1.3" }
alloy-rpc-types-eth = { version = "1.1.3" }
alloy-transport = { version = "1.1.3", features = ["throttle"] }
alloy-transport-http = { version = "1.1.3" }
alloy-signer = { version = "1.1.3" }
alloy-signer-local = { version = "1.1.3" }
alloy-contract = { version = "1.1.3" }
alloy-sol-types = { version = "1.4.1", features = ["json"] }

tracing = { workspace = true }
tracing-core = { workspace = true }
