[package]
name = "facilitator"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }

x402-types = { path = "../crates/x402-types" }
x402-facilitator-local = { path = "../crates/x402-facilitator-local" }
x402-chain-eip155 = { path = "../crates/chains/x402-chain-eip155" }
x402-chain-solana = { path = "../crates/chains/x402-chain-solana" }
x402-chain-aptos = { path = "../crates/chains/x402-chain-aptos" }

axum = { workspace = true }
clap = { version = "4.5", features = ["derive", "env"] }
tower-http = { version = "0.6.6", features = ["trace", "cors"] }
rustls = { version = "0.23" }
