[package]
name = "x402-reqwest-example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
x402-reqwest = { version = "0.4" }
x402-rs = { version = "0.10" }
reqwest = { version = "0.12.20" }
tokio = { version = "1.45.1" }
dotenvy = { version = "0.15.7" }
solana-sdk = { version = "2.3.1", features = ["full"] }
spl-token = { version = "8.0.0" , features = ["no-entrypoint"] }
spl-token-2022 = { version = "9.0.0" , features = ["no-entrypoint"] }
solana-client = { version = "2.3.7" }

# EVM: Alloy
alloy-signer-local = { version = "1.1.3" }

bincode = { version = "1.3.3" } # Older version due to compatibility with solana-sdk
