[package]
name = "x402-reqwest-example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
x402-rs = { path = "../../" }
x402-reqwest = { path = "../../crates/x402-reqwest", features = ["telemetry"] }
reqwest = { version = "0.12.25" }
tokio = { version = "1.45.1" }
dotenvy = { version = "0.15.7" }

# EVM: Alloy
alloy-signer-local = { version = "1.1.3" }

# Solana
solana-client = { version = "3.1.4" }
solana-keypair = { version = "3.1.0" }
