[package]
name = "x402-reqwest-example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
x402-rs = { path = "../../" }
reqwest = { version = "0.12.25" }
tokio = { version = "1.45.1" }
dotenvy = { version = "0.15.7" }
http = { version = "1.4.0" }
reqwest-middleware = { version = "0.4.2" }
async-trait = { version = "0.1.88" }
serde_json = { version = "1.0.145" }

# EVM: Alloy
alloy-primitives = { version = "1.4.1" }
alloy-signer-local = { version = "1.1.3" }
alloy-signer = { version = "1.1.3" }
alloy-sol-types = { version = "1.4.1" }
ruint = { version = "1.17.0"}
rand = { version = "0.9.2" }
thiserror = { version = "2.0.17" }

# Solana
solana-rpc-client = { version = "2.3.13" }
solana-keypair = { version = "2.2.3" }
serde = { version = "1.0.228", features = ["derive"] }
